import telnetlib
import time
from tkinter import messagebox

def telnet_setupmdi():
    messagebox.showinfo(title="Picturall Media Manager", message="The Picturall setup start!")
    HOST = "192.168.2.140"
    PORT = "11000"

    tn=telnetlib.Telnet()
    tn.open(HOST, PORT)

    time.sleep(0.1)
    tn.write("wait_startup\n".encode('utf-8'))
    time.sleep(0.1) 
    print("canva setup")
    tn.write("set canvas1 position8 x=0.0,y=0.5,w=0.25,h=0.15625,rotation=0.0,enabled=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 position1 x=0.25,y=0.5,w=0.25,h=0.15625,rotation=0.0,enabled=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 position2 x=0.5,y=0.5,w=0.25,h=0.15625,rotation=0.0,enabled=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 position3 x=0.75,y=0.5,w=0.25,h=0.15625,rotation=0.0,enabled=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 position4 x=0.0,y=0.34375,w=0.25,h=0.15625,rotation=0.0,enabled=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 position5 x=0.25,y=0.359375,w=0.25,h=0.140625,rotation=0.0,enabled=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 position6 x=0.5,y=0.34375,w=0.25,h=0.15625,rotation=0.0,enabled=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 position7 x=0.75,y=0.34375,w=0.25,h=0.15625,rotation=0.0,enabled=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("transaction begin\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 grouping8 column=0,row=0,group=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 grouping1 column=1,row=0,group=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 grouping2 column=2,row=0,group=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 grouping3 column=3,row=0,group=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 grouping4 column=0,row=1,group=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 grouping5 column=1,row=1,group=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 grouping6 column=2,row=1,group=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 grouping7 column=3,row=1,group=1\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("transaction commit\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set canvas1 display_focus display=0\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set gpu1 pixel_space w=7680,h=2400,max_size=35.0\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set gpu2 pixel_space w=7680,h=2400,max_size=35.0\n".encode('utf-8'))
    time.sleep(0.5)



    tn.write("set source1 selection slot=1,collection=252\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source2 selection slot=2,collection=252\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source3 selection slot=3,collection=252\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source4 selection slot=4,collection=252\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source5 selection slot=5,collection=252\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source6 selection slot=6,collection=252\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source7 selection slot=7,collection=252\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source8 selection slot=8,collection=252\n".encode('utf-8'))
    time.sleep(0.5)


    tn.write("set source1 control play_state_req=0\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source2 control play_state_req=0\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("set source3 control play_state_req=0\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("set source4 control play_state_req=0\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("set source5 control play_state_req=0\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("set source6 control play_state_req=0\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("set source7 control play_state_req=0\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("set source8 control play_state_req=0\n".encode('utf-8')) 
    time.sleep(0.5)


    tn.write("fullscreen layer1 1 stretch\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("fullscreen layer2 2 stretch\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("fullscreen layer3 3 stretch\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("fullscreen layer4 4 stretch\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("fullscreen layer5 5 stretch\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("fullscreen layer6 6 stretch\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("fullscreen layer7 7 stretch\n".encode('utf-8')) 
    time.sleep(0.5)
    tn.write("fullscreen layer8 8 stretch\n".encode('utf-8')) 
    time.sleep(0.5)

    tn.write("set canvas1 test_system_info enabled=0\n".encode('utf-8')) 
    time.sleep(0.5)

    tn.write("set source1 control media_end_action=10\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source2 control media_end_action=10\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source3 control media_end_action=10\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source4 control media_end_action=10\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source5 control media_end_action=10\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source5 control media_end_action=10\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source6 control media_end_action=10\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source7 control media_end_action=10\n".encode('utf-8'))
    time.sleep(0.5)
    tn.write("set source8 control media_end_action=10\n".encode('utf-8'))
 
    time.sleep(1)
    tn.write("logout\n".encode('utf-8')) 
    print(tn.read_all())
    tn.close()
    print("setup done!")
    messagebox.showinfo(title="Picturall Media Manager", message="The Picturall setup is done!")